# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_text', models.CharField(max_length=200)),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
    ]
